#Promo Page
buttonMasuk = '//*[@id="root"]/div/div[2]/div/div/div[2]/form/button'
buttonCreatePromo = '//*[@id="root"]/div/div[3]/div/div/div[2]/a'
menuPromo = '//*[@id="root"]/div/div[2]/div[7]/div[2]/div'
toggleJam = '//*[@id="root"]/div/div[3]/div/div/form/div[2]/div[1]/div[2]/div/div/div[6]/div[1]/div/span/span[1]/span/input'
buttonFilter = '//*[@id="root"]/div/div[3]/div/div/form/div[2]/div[2]/div[2]/div/div[1]/button'
buttonSimpan = '//*[@id="root"]/div/div[3]/div/div/form/div[3]/div/button'
toggleDiskon = '//*[@id="root"]/div/div[3]/div/div/form/div[2]/div[1]/div[2]/div/div/div[1]/div[1]/div/span[1]/span[1]/span/input'
buttonRincian = '/html/body/div[1]/div/div[3]/div/div/div[4]/div/div/div/div[2]/div[3]/div/div/div/div/div/div/div[5]/a'
searchName = '/html/body/div[3]/div/div[2]/div/div/div[5]/div/div/input'
fiturFilter = '/html/body/div[3]/div/ul/li[4]'
buttonAturJadwal = '//*[@id="root"]/div/div[3]/div/div/form/div[2]/div[2]/div[3]/div/div[2]/a'
buttonHapus = '//*[@id="root"]/div/div[3]/div/div/form/div[2]/div[2]/div[3]/div/div[2]/button'
